# Generated by Django 4.2.1 on 2025-08-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(null=True)),
                ('logo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.CharField(max_length=31)),
                ('max', models.CharField(max_length=31)),
                ('currency', models.CharField(max_length=31)),
                ('unit', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('benefits', models.TextField(null=True)),
                ('employmentType', models.CharField(max_length=63)),
                ('image', models.URLField(null=True)),
                ('workHours', models.CharField(max_length=31, null=True)),
                ('url', models.URLField()),
                ('validThrough', models.DateTimeField(null=True)),
                ('posted_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('applicantLocationRequirements', models.ManyToManyField(blank=True, related_name='requirement_job_location', to='jobs.location')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='jobs.company')),
                ('jobLocation', models.ManyToManyField(related_name='job_location', to='jobs.location')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='jobs.salary')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='jobs.tag')),
            ],
        ),
    ]
